const getters = {
  sidebar: state => state.app.sidebar,
  size: state => state.app.size,
  device: state => state.app.device,
  loadingCount: state => state.app.loadingCount,
  loadingDelayed: state => state.app.loadingDelayed,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  introduction: state => state.user.introduction,
  roles: state => state.user.roles,
  userInfo: state => state.user.userInfo,
  tenantId: state => state.user.userInfo.organizationId,
  permission_routes: state => state.permission.routes,
  errorLogs: state => state.errorLog.logs,
  isSuperAdmin: state => state.user.isSuperAdmin,
  userPermissions: state => state.user.permissions,
  userPermissionBtns: state => state.user.permissionBtns,
};
export default getters;
